CXX = g++
CXXFLAGS = -std=c++20 -Wall -Wextra -Iinclude

SRC = $(wildcard src/*.cpp)
OBJ = $(SRC:.cpp=.o)

TARGET = tcp_sever

$(TARGET) : $(OBJ)
	$(CXX) $(OBJ) -o $(TARGET)


%.0: %.cpp
	$(CXX) $(CXXFLAGS) -c $c -o $@

clean:
	rm -f src.*.o $(TARGET)